### ISSUE TITLE
Bundle Hexchat

### ISSUE THREAD

**Issue by philipzae** [Xubuntu/xubuntu-default-settings#12]
Seeding patch is [here](https://github.com/philipzae/xubuntu-seed/commit/8d33347490e062412bffe4498830cc1b8a6817fc) but we also need to bundle a ~/.config/hexchat/servlist.conf with auto joining of #xubuntu.

![image](https://imgur.com/7OWWM2B.png)

**Comment by bluesabre** [comment]
You mentioned before that another distro (was it Mint?) included an autojoin servlist.conf... can you track that down?

**Comment by philipzae** [comment]
Yes Linux Mint. It has a hexchat.conf and servlist.conf in ~/.config. [hexchat-linuxmint.zip](https://github.com/Xubuntu/xubuntu-default-settings/files/6012606/hexchat-linuxmint.zip)

The hexchat.conf has gui_slist_fav (show favorites only) and gui_slist_skip (skip network list on startup) as 1 and servlist.conf has F=91 set for the linux mint server so that it auto joins it.

![image](https://user-images.githubusercontent.com/4412114/108552776-31118b80-730b-11eb-9adb-2af34968073f.png)

**Comment by bluesabre** [comment]
This patch should give the autojoin and configuration we need.

[0001-Add-hexchat-config-to-preselect-freenode-and-autojoi.txt](https://github.com/Xubuntu/xubuntu-default-settings/files/6021761/0001-Add-hexchat-config-to-preselect-freenode-and-autojoi.txt)

**Comment by philipzae** [comment]
F=91 isn't set for the server in line 249 of the patch.

Guess the only real way to test this out is to push it into the ISO and check on the next daily build.

**Comment by bluesabre** [comment]
The patch I provided came from testing it directly by adding these files to ~/.config/hexchat and testing it. I opted out of automatically logging in to the server to give the user more control.

**Comment by bluesabre** [comment]
Uploaded xubuntu-default-settings and xubuntu-meta changes that add Hexchat to the seed. Closing this one out.
