### ISSUE TITLE
New panel additions

### ISSUE THREAD

**Issue by philipzae** [Xubuntu/xubuntu-default-settings#14]
Preinstall xfce4-clipman-plugin and xfce4-appmenu-plugin, with clipman being in the panel and appmenu being available to the new Cupertino panel layout. Part of issue #5.

**Comment by philipzae** [comment]
Seeds patch: https://github.com/philipzae/xubuntu-seed/commit/1d412bfd17ddc9a599753b0084fb03a361365831

**Comment by bluesabre** [comment]
Closing in favor of https://github.com/Xubuntu/xubuntu-seed/issues/23
