### ISSUE TITLE
Menu Updates

### ISSUE THREAD

**Issue by philipzae** [Xubuntu/xubuntu-default-settings#6]
Changes needing to be made to the whisker menu properties and applications list.
https://docs.google.com/document/d/1hzvQURi8l--GrfqsxP9c0tWNUzrkbZjZTiVxGUegALg/edit#heading=h.gnytyvrq9rz4

**Comment by philipzae** [comment]
When it comes to the applications list, I think these entries should be hidden from the menu.

- **TeXInfo** in Applications
- **LibreOffice Math** in Education
- **PulseAudio** in Multimedia (assuming we get the _Sound_ entry in Settings Manager - issue #7)

**Comment by Skif-off** [comment]
> **File Renamer** in System - main use is within thunar

Don't touch please, some people use other file manages, but it's good tool.

**Comment by bluesabre** [comment]
LibreOffice Math should likewise stay. This seems like a normal and usable application, hiding it just because its the only entry in a menu doesn't seem like a good idea.

Please update your patch to exclude the LibreOffice Math and File Renamer exclusions.

**Comment by philipzae** [comment]
LibreOffice Math is already in the Office menu, so having it in one location, like all other apps, is what is wanted and if the choice was between the Office and Education menus, Office menu is better choice.

**Comment by bluesabre** [comment]
Actually, with today's Hirsute daily image, I don't see any Education menu. LibreOffice Math only in Office.

![image](https://user-images.githubusercontent.com/1894517/108574340-23e1a600-72e5-11eb-9c27-d6123af2e89b.png)

**Comment by philipzae** [comment]
Patch updated.
