### ISSUE TITLE
I guess an ISO is too much to ask.

### ISSUE THREAD

**Issue by AnonymousRonin** [Xubuntu/xubuntu-default-settings#76]
You do know you can't load an iso in virtualbox, right?  This is clearly going to be more hassle than it's worth.

**Comment by bluesabre** [comment]
VirtualBox supports installing from ISO. If you're having difficulty, you should refer to the [documentation](https://www.virtualbox.org/wiki/End-user_documentation) or seek assistance from the [community](https://www.virtualbox.org/wiki/Community).
